name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clear npm cache (fixes permission issues)
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install
        env:
          CI: true  # Prevents interactive prompts

      - name: Increase memory limits (fixes out-of-memory issues)
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npm run build

      - name: Run tests (Optional: Remove if you have no tests)
        run: npm test || echo "Tests failed, continuing..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
