name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs when you push to the main branch
  pull_request:
    branches:
      - main  # Runs when a PR is made to main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then 
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping dependency installation."
          fi
          pip install pytest  # Ensure pytest is installed

      - name: Run Tests
        run: |
          if ls tests/test_*.py 1> /dev/null 2>&1; then
            pytest
          else
            echo "No test files found, skipping tests."
          fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Render
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
